// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct Particle
{
    float3 position;
    float3 predicted_position;
    float3 velocity;
    float inverse_mass;
};

RWStructuredBuffer<Particle> particles;

[numthreads(64,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // test, move particles up
    particles[id.x].position.y += 0.001;
}
